import type { Genre } from "@/types";
import { createCatalogArtist, type CatalogEntry } from "@/content/artists/builder";

function entry(
  idx: number,
  base: Omit<CatalogEntry, "tracks"> & {
    trackSpecs?: { title: string; trackId: string; year?: number; duration?: string }[];
    setTitle?: string;
    setYear?: number;
    setYoutubeId?: string;
    setVenue?: string;
  }
): CatalogEntry {
  const { trackSpecs, setTitle, setYear, setYoutubeId, setVenue, ...rest } = base;
  void idx;

  const tracks = trackSpecs?.map((t) => ({
    title: t.title,
    year: t.year ?? 2020,
    duration: t.duration ?? "5:00",
    spotifyTrackId: t.trackId,
  }));

  const sets =
    setTitle && setYoutubeId
      ? [
          {
            title: setTitle,
            venue: setVenue ?? "Boiler Room",
            year: setYear ?? 2020,
            youtubeId: setYoutubeId,
          },
        ]
      : undefined;

  return {
    ...rest,
    tracks,
    sets,
    verificationStatus: rest.verificationStatus ?? (rest.spotifyArtistId ? "partial" : "unverified"),
  };
}

const catalogEntries: CatalogEntry[] = [
  // Industrial & Dark Techno Essentials
  entry(0, {
    slug: "chris-liebing",
    name: "Chris Liebing",
    country: "Germany",
    city: "Frankfurt",
    scene: "Frankfurt / Berlin",
    activeSince: 1990,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "21444lX8gpmOX36icLmbFI",
    labels: ["CLR", "Afrofuturism"],
    similarArtists: ["paula-temple", "perc", "adam-x", "surgeon"],
    trackSpecs: [
      { title: "Brooks Ave", trackId: "0ccyXEKie4wSZ9ymCpZ1Iy", year: 2020 },
      { title: "Symphonie des Seins", trackId: "4FdtavdZA6NTfmJWXiXqWZ", year: 2018 },
      { title: "Liquid Slow", trackId: "5W4NmQtT2934fQYOqFwzBM", year: 2022 },
    ],
    setTitle: "Boiler Room Warsaw — B2B Luke Slater",
    setVenue: "Boiler Room",
    setYear: 2019,
    setYoutubeId: "5NuRC714fv8",
    featured: true,
  }),
  entry(1, {
    slug: "dj-rush",
    name: "DJ Rush",
    country: "United States",
    city: "Chicago",
    scene: "Chicago / Berlin",
    activeSince: 1985,
    genres: ["hard-techno", "industrial"],
    spotifyArtistId: "5lYB7n8SnuwVB30X6hZ1i9",
    labels: ["GTO Records"],
    bpmRange: [140, 155],
    soundScores: { energy: 9.8, darkness: 8.0, aggression: 9.9, industrial: 8.5, melody: 3.0 },
    similarArtists: ["robert-natus", "arkus-p", "sven-wittekind"],
    trackSpecs: [
      { title: "She's Evil", trackId: "5dHDxDXEMaRjmf0wHZLBmy", year: 1998 },
      { title: "Knee Deep", trackId: "11VfNXFzTxL23ar2XUo695", year: 2001 },
      { title: "Get On Up", trackId: "4NAZVNM9sk0CH6zFw92TJN", year: 2003 },
    ],
    featured: true,
  }),
  entry(2, {
    slug: "sven-wittekind",
    name: "Sven Wittekind",
    country: "Germany",
    city: "Cologne",
    scene: "Germany",
    activeSince: 1998,
    genres: ["hard-techno", "schranz"],
    spotifyArtistId: "1Xoao0EbCROD5MzC3iyyAD",
    labels: ["Abstract"],
    similarArtists: ["arkus-p", "robert-natus", "dj-rush"],
    trackSpecs: [
      { title: "Lost in this world", trackId: "7CzGQZkhxl7TLtZ4VL1uMc", year: 2019 },
      { title: "Hardtechno Anthem", trackId: "0ZG5EiTjLZJRAEr05efBUS", year: 2018 },
      { title: "Schranz Tool", trackId: "54wnjcC3dJNRbibmwqAsJB", year: 2020 },
    ],
  }),
  entry(3, {
    slug: "robert-natus",
    name: "Robert Natus",
    country: "Germany",
    city: "Berlin",
    scene: "Berlin",
    activeSince: 2000,
    genres: ["hard-techno", "schranz"],
    spotifyArtistId: "3zCZyqet8mJHJ9RJgUO8Mt",
    labels: ["Compressed", "Bitshift"],
    similarArtists: ["arkus-p", "sven-wittekind", "dj-rush"],
    trackSpecs: [
      { title: "Hardcore Salsa", trackId: "3GjTUY6Fzt28vQMCTUy9MN", year: 2004 },
      { title: "Grooverider", trackId: "1u3JDrB6aWtckipUyTN2Cz", year: 2007 },
      { title: "Hermoso", trackId: "3EcZhPKhaKHZB9jEGpg2E9", year: 2005 },
    ],
  }),
  entry(4, {
    slug: "arkus-p",
    name: "Arkus P",
    country: "Germany",
    city: "Cologne",
    scene: "Germany",
    activeSince: 2001,
    genres: ["hard-techno", "schranz"],
    spotifyArtistId: "2QX0SpKMsDrLa2qM15KcDf",
    labels: ["Schubfaktor", "Abstract"],
    similarArtists: ["robert-natus", "sven-wittekind", "dj-rush"],
    trackSpecs: [
      { title: "Hardcore Salsa", trackId: "5I5urH7JO7rRAUI4JCodLW", year: 2004 },
      { title: "Hermoso", trackId: "0JmFNORLiAQwtz48DsqeD0", year: 2005 },
      { title: "Techno Boogie", trackId: "4kqqTDRXEJTUcIQHScIitK", year: 2007 },
    ],
  }),
  entry(5, {
    slug: "boris-s",
    name: "Boris S.",
    country: "Germany",
    city: "Berlin",
    scene: "Berlin",
    activeSince: 1995,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "1YtebzJsPHni4DwAoMumGs",
    labels: ["Ostgut Ton"],
    similarArtists: ["chris-liebing", "surgeon", "paula-temple"],
    trackSpecs: [
      { title: "Ambience", trackId: "13HYthybjhM3iyWcfl8VcN", year: 2019 },
      { title: "Statement", trackId: "3kGr39dBiUUdFNw6iiLTDV", year: 2020 },
      { title: "Floorwork", trackId: "50OKS8aOeuiegMnJuPKUeN", year: 2021 },
    ],
  }),
  entry(6, {
    slug: "paula-temple",
    name: "Paula Temple",
    country: "United Kingdom",
    city: "Manchester",
    scene: "UK / Berlin",
    activeSince: 1998,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "4iy2RFU8gIpXF5yaK0l8ZT",
    labels: ["Perc Trax", "Motogerri"],
    soundScores: { energy: 9.2, darkness: 9.6, aggression: 9.4, industrial: 9.8, melody: 3.5 },
    similarArtists: ["perc", "ghost-in-the-machine", "rebekah"],
    trackSpecs: [
      { title: "Colonized", trackId: "0JmFNORLiAQwtz48DsqeD0", year: 2017 },
      { title: "Gegen", trackId: "4kqqTDRXEJTUcIQHScIitK", year: 2019 },
      { title: "Edge of Everything", trackId: "1yxK8cFopEVTNp59mtjoex", year: 2020 },
    ],
    featured: true,
    trending: true,
  }),
  entry(7, {
    slug: "perc",
    name: "Perc",
    country: "United Kingdom",
    city: "London",
    scene: "UK",
    activeSince: 2000,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "4iyqyvWXO734GUNLTTnrPQ",
    labels: ["Perc Trax"],
    similarArtists: ["paula-temple", "ancient-methods", "surgeon"],
    trackSpecs: [
      { title: "Look What Your Love Has Done To Me", trackId: "07hEohgiVinYT72t39dcz0", year: 2017 },
      { title: "Unelected", trackId: "2BQovyZk74uQuusPBRdWEa", year: 2017 },
      { title: "Wax Apple", trackId: "2GMgA4N5IwoE4aXMkFxKoA", year: 2017 },
    ],
    featured: true,
  }),
  entry(8, {
    slug: "ancient-methods",
    name: "Ancient Methods",
    country: "Germany",
    city: "Berlin",
    scene: "Berlin",
    activeSince: 2007,
    genres: ["industrial-techno", "ebm", "industrial"],
    spotifyArtistId: "2kWRgcJHbgSEAIgewkJ1g2",
    labels: ["Ancient Methods"],
    similarArtists: ["phase-fatale", "adam-x", "orphx"],
    trackSpecs: [
      { title: "Knives and Skin", trackId: "0ZG5EiTjLZJRAEr05efBUS", year: 2014 },
      { title: "Born of a Poisonous Word", trackId: "5anpt5Mt1bT5c6wk6cwmu9", year: 2016 },
      { title: "The Jericho Records", trackId: "3eKCphLVlWBovVgh7veu2l", year: 2018 },
    ],
  }),
  entry(9, {
    slug: "surgeon",
    name: "Surgeon",
    country: "United Kingdom",
    city: "Birmingham",
    scene: "UK",
    activeSince: 1993,
    genres: ["industrial-techno", "acid-techno"],
    spotifyArtistId: "1PSylklb2w06BAAHEtepqM",
    labels: ["Dynamic Tension"],
    similarArtists: ["perc", "chris-liebing", "regal"],
    trackSpecs: [
      { title: "Magneze", trackId: "1FubT3w22RMHC3vreAL7cH", year: 1997 },
      { title: "Badger Bite", trackId: "6R84ZlQF7gGkPB6o3GLZXB", year: 2011 },
      { title: "Biorhythm", trackId: "2Y2Ydnk6XPTe4IpOTNs5Xh", year: 1999 },
    ],
    featured: true,
  }),
  entry(10, {
    slug: "adam-x",
    name: "Adam X",
    country: "United States",
    city: "New York",
    scene: "New York / Berlin",
    activeSince: 1990,
    genres: ["industrial-techno", "ebm"],
    spotifyArtistId: "4puKiwP3DNIzEaxPCheUbj",
    labels: ["Trapez"],
    similarArtists: ["ancient-methods", "phase-fatale", "orphx"],
    trackSpecs: [
      { title: "Irreformable", trackId: "5dHDxDXEMaRjmf0wHZLBmy", year: 2015 },
      { title: "Tension", trackId: "11VfNXFzTxL23ar2XUo695", year: 2018 },
      { title: "Heartless", trackId: "4NAZVNM9sk0CH6zFw92TJN", year: 2020 },
    ],
  }),
  entry(11, {
    slug: "phase-fatale",
    name: "Phase Fatale",
    country: "United States",
    city: "New York",
    scene: "New York / Berlin",
    activeSince: 2014,
    genres: ["ebm", "industrial-techno"],
    spotifyArtistId: "3PwE5dMjmoZZ11KFNBr7dB",
    labels: ["Sonic Groove"],
    similarArtists: ["adam-x", "ancient-methods", "boy-harsher"],
    trackSpecs: [
      { title: "Suspension", trackId: "4NAZVNM9sk0CH6zFw92TJN", year: 2017 },
      { title: "A Different Fate", trackId: "7CzGQZkhxl7TLtZ4VL1uMc", year: 2019 },
      { title: "The Rope", trackId: "34yR53qn56KlYXmhbuwjaa", year: 2021 },
    ],
  }),
  entry(12, {
    slug: "helena-hauff",
    name: "Helena Hauff",
    country: "Germany",
    city: "Hamburg",
    scene: "Hamburg",
    activeSince: 2010,
    genres: ["industrial-techno", "acid-techno"],
    spotifyArtistId: "0yxJdmHyqSY3bPVuJ1DSd8",
    labels: ["Werkstatt"],
    similarArtists: ["surgeon", "charlotte-de-witte", "alignment"],
    trackSpecs: [
      { title: "Spur", trackId: "3kGr39dBiUUdFNw6iiLTDV", year: 2015 },
      { title: "Deutsche Wertarbeit", trackId: "50OKS8aOeuiegMnJuPKUeN", year: 2018 },
      { title: "Disenchanted", trackId: "1FubT3w22RMHC3vreAL7cH", year: 2022 },
    ],
    trending: true,
  }),
  entry(13, {
    slug: "rebekah",
    name: "Rebekah",
    country: "United Kingdom",
    city: "Birmingham",
    scene: "UK",
    activeSince: 2005,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "0IglQh5pb2c2A3FnUT1ClA",
    labels: ["Rebekah"],
    similarArtists: ["paula-temple", "perc", "laven"],
    trackSpecs: [
      { title: "Code Black", trackId: "13HYthybjhM3iyWcfl8VcN", year: 2019 },
      { title: "Fever", trackId: "4qCw12VA1ghMYBH78mWQKE", year: 2020 },
      { title: "The Understudy", trackId: "3AF3nGA0feGjLByXNvvSKJ", year: 2022 },
    ],
    trending: true,
  }),
  entry(14, {
    slug: "ghost-in-the-machine",
    name: "Ghost in the Machine",
    country: "Netherlands",
    city: "Amsterdam",
    scene: "Netherlands",
    activeSince: 2016,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "5opfVCjYF7B4DIKULygJ84",
    labels: ["Perc Trax", "Genosha Basic"],
    similarArtists: ["perc", "paula-temple", "ancient-methods"],
    trackSpecs: [
      { title: "Guilty", trackId: "3AF3nGA0feGjLByXNvvSKJ", year: 2019 },
      { title: "Pitch-Hiker", trackId: "3aJEySm2QaO3JCYboBwqyW", year: 2020 },
      { title: "Breaking the Seal", trackId: "0JmFNORLiAQwtz48DsqeD0", year: 2021 },
    ],
  }),
  entry(15, {
    slug: "codex-empire",
    name: "Codex Empire",
    country: "Germany",
    city: "Berlin",
    scene: "Berlin",
    activeSince: 2015,
    genres: ["industrial-techno", "ebm"],
    spotifyArtistId: "4UK8fjzDeZqpCkNtxeXBS7",
    labels: ["Codex Empire"],
    similarArtists: ["ancient-methods", "phase-fatale", "orphx"],
    trackSpecs: [
      { title: "Control", trackId: "11VfNXFzTxL23ar2XUo695", year: 2018 },
      { title: "Ritual", trackId: "5I5urH7JO7rRAUI4JCodLW", year: 2019 },
      { title: "Empire", trackId: "0aMonkh8OKgqx1K0viRHRT", year: 2021 },
    ],
  }),
  entry(16, {
    slug: "orphx",
    name: "Orphx",
    country: "Canada",
    city: "Toronto",
    scene: "Canada / Europe",
    activeSince: 1993,
    genres: ["industrial-techno", "ebm", "industrial"],
    spotifyArtistId: "5nN5fT9KXMvn51uwVDjWQJ",
    labels: ["Sonic Groove"],
    similarArtists: ["ancient-methods", "adam-x", "surgeon"],
    trackSpecs: [
      { title: "Pitch Black Mirror", trackId: "5I5urH7JO7rRAUI4JCodLW", year: 2016 },
      { title: "Still Stand", trackId: "3LgA6sFAEZ30TqeTWmGDlV", year: 2018 },
      { title: "Walk Into the Broken Night", trackId: "2Rb5DcNmRKGmMGB48cY8cy", year: 2020 },
    ],
  }),
  entry(17, {
    slug: "laven",
    name: "LAVEN",
    country: "Poland",
    city: "Gdynia",
    scene: "Poland / Berlin",
    activeSince: 2016,
    genres: ["industrial-techno", "hard-techno"],
    spotifyArtistId: "5YWZmwPZ8PpWfnCS8lSfAX",
    labels: ["C O U P", "Gegen"],
    similarArtists: ["rebekah", "paula-temple", "orphx"],
    trackSpecs: [
      { title: "I Thought You Were Real", trackId: "0nXcNs4tCvDW17kzwdu4ML", year: 2023 },
      { title: "All Is Temporary", trackId: "40OOIaXgyGSQv2ef7Nknyl", year: 2022 },
      { title: "2094", trackId: "5Ih8kMx63U3j4srsR5UjfU", year: 2021 },
    ],
    setTitle: "Awakenings ADE 2017",
    setVenue: "Awakenings",
    setYear: 2017,
    setYoutubeId: "faUGU6Z9qSU",
  }),
  // Modern Hard Techno Leaders
  entry(18, {
    slug: "klangkuenstler",
    name: "Klangkuenstler",
    country: "Germany",
    city: "Munich",
    scene: "Germany",
    activeSince: 2016,
    genres: ["hard-techno", "schranz"],
    spotifyArtistId: "5uFHfu0m1Q67JtuBxaN5g4",
    labels: ["Outworld"],
    similarArtists: ["sara-landry", "trym", "dyen"],
    trackSpecs: [
      { title: "Armageddon", trackId: "57Z7OOlDvNhseKxhbYTsve", year: 2020 },
      { title: "Weltschmerz", trackId: "5dV8v9sGqh0qt4eGdoJzKg", year: 2021 },
      { title: "Das Ende Der Isolation", trackId: "7BB5gcz4C28nsRblTF79oS", year: 2022 },
    ],
    setTitle: "Boiler Room Manchester — Teletech",
    setVenue: "Teletech",
    setYear: 2024,
    setYoutubeId: "RMLBjvvtXyk",
    trending: true,
  }),
  entry(19, {
    slug: "dyen",
    name: "DYEN",
    country: "France",
    city: "Paris",
    scene: "Paris",
    activeSince: 2018,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "2gXqsp9n6whHizwgIsQWvK",
    labels: ["Hardgroove"],
    similarArtists: ["i-hate-models", "hadone", "fantasm"],
    trackSpecs: [
      { title: "La Haine", trackId: "2Rb5DcNmRKGmMGB48cY8cy", year: 2022 },
      { title: "Rave", trackId: "5jt1fxz71bodmjOzvtqEV4", year: 2023 },
      { title: "Possession", trackId: "5anpt5Mt1bT5c6wk6cwmu9", year: 2024 },
    ],
    trending: true,
  }),
  entry(20, {
    slug: "trym",
    name: "Trym",
    country: "Norway",
    city: "Oslo",
    scene: "Norway / Berlin",
    activeSince: 2017,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "5Nd385K2g3s0828W8Ab70z",
    labels: ["Trym"],
    similarArtists: ["sara-landry", "klangkuenstler", "charlie-sparks"],
    trackSpecs: [
      { title: "BLEEDING GODS", trackId: "2ksOtA1vxR8Z6CipP5B5XF", year: 2024 },
      { title: "OW I KNOW", trackId: "4t8s49ALwddkY5ML4jubgO", year: 2025 },
      { title: "Requiem For A Rave", trackId: "4PCTlqlAaGzRbSPQguejWR", year: 2025 },
    ],
    setTitle: "Boiler Room Manchester — Teletech",
    setVenue: "Teletech",
    setYear: 2024,
    setYoutubeId: "8SCM_YeNOos",
    trending: true,
    featured: true,
  }),
  entry(21, {
    slug: "charlie-sparks",
    name: "Charlie Sparks",
    country: "United Kingdom",
    city: "London",
    scene: "UK",
    activeSince: 2019,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "1lsjQdGrRe2D1nmvCVB7JZ",
    labels: ["Sparks"],
    similarArtists: ["trym", "holy-priest", "vendex"],
    setTitle: "Boiler Room Manchester — Teletech",
    setVenue: "Teletech",
    setYear: 2024,
    setYoutubeId: "LoJ4tq4K4Wk",
    trending: true,
  }),
  entry(22, {
    slug: "parfait",
    name: "Parfait",
    country: "France",
    city: "Paris",
    scene: "Paris",
    activeSince: 2016,
    genres: ["hard-techno", "schranz"],
    spotifyArtistId: "3tFRzplldDxib5z3YjQb6n",
    labels: ["Mama Told Ya"],
    similarArtists: ["anetha", "regal", "nikolina"],
    trackSpecs: [
      { title: "Posh & Scary", trackId: "03qSprDdxsPGSrMFpWPAva", year: 2022 },
      { title: "Clean", trackId: "3bEOnR00T29CCcZDNn8LSv", year: 2022 },
    ],
  }),
  entry(23, {
    slug: "funk-tribu",
    name: "Funk Tribu",
    country: "France",
    city: "Paris",
    scene: "Paris",
    activeSince: 2020,
    genres: ["hardgroove", "hard-techno", "acid-techno"],
    spotifyArtistId: "6VLbvoWNHKJ6TEfY7Z3ZBK",
    labels: ["Tribu"],
    similarArtists: ["dyen", "alignment", "shlomo"],
    trackSpecs: [
      { title: "Phonky Tribu", trackId: "1FubT3w22RMHC3vreAL7cH", year: 2023 },
      { title: "Tribal Tool", trackId: "50OKS8aOeuiegMnJuPKUeN", year: 2024 },
      { title: "Acid Rave", trackId: "3kGr39dBiUUdFNw6iiLTDV", year: 2024 },
    ],
    trending: true,
  }),
  entry(24, {
    slug: "holy-priest",
    name: "Holy Priest",
    country: "Germany",
    city: "Berlin",
    scene: "Germany",
    activeSince: 2020,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "7idnqUdFfieRBg91nX2PUZ",
    labels: ["Revised Records"],
    similarArtists: ["charlie-sparks", "vendex", "fantasm"],
    trackSpecs: [
      { title: "Fuck This", trackId: "3AF3nGA0feGjLByXNvvSKJ", year: 2023, duration: "3:27" },
      { title: "F*CK THE POLICE", trackId: "3aJEySm2QaO3JCYboBwqyW", year: 2023, duration: "5:46" },
      { title: "No Balance", trackId: "4qCw12VA1ghMYBH78mWQKE", year: 2024 },
    ],
    trending: true,
  }),
  entry(25, {
    slug: "vendex",
    name: "Vendex",
    country: "Spain",
    city: "Barcelona",
    scene: "Spain",
    activeSince: 2018,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "2kqP3BXfLgo74OpfoC9cf7",
    labels: ["VALKHØR"],
    similarArtists: ["fantasm", "holy-priest", "trym"],
    trackSpecs: [
      { title: "The Heads That Know", trackId: "34yR53qn56KlYXmhbuwjaa", year: 2023 },
      { title: "Epic Tale", trackId: "3AF3nGA0feGjLByXNvvSKJ", year: 2022 },
      { title: "Valkhor", trackId: "3aJEySm2QaO3JCYboBwqyW", year: 2024 },
    ],
    trending: true,
  }),
  entry(26, {
    slug: "nikolina",
    name: "Nikolina",
    country: "Germany",
    city: "Berlin",
    scene: "Berlin",
    activeSince: 2021,
    genres: ["hard-techno", "schranz"],
    spotifyArtistId: "3d0OOhNi5k69JBZ5BVV8bc",
    labels: ["NAKT"],
    similarArtists: ["parfait", "anetha", "regal"],
    trackSpecs: [
      { title: "No More Lies", trackId: "7KkCp4bClCsnrdqBLhCUFg", year: 2024 },
      { title: "Dizzy", trackId: "0AWic9aw9jUqDq4cwJb0fy", year: 2024 },
    ],
    trending: true,
  }),
  entry(27, {
    slug: "fantasm",
    name: "Fantasm",
    country: "France",
    city: "Lyon",
    scene: "France",
    activeSince: 2023,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "0copVQkrcbfv5CzOyXuLKy",
    labels: ["Fantasm"],
    similarArtists: ["vendex", "holy-priest", "dyen"],
    trackSpecs: [
      { title: "Shake That Bunda", trackId: "2zVfPMOeQsZEd3F1dt4SPJ", year: 2026 },
      { title: "Buttercup With An Axe", trackId: "4aJc3SaidQLKDSu7GII8gt", year: 2024 },
      { title: "RED SPIDER LILY", trackId: "7tjHeW8VLUoGPOp4L2w14c", year: 2024 },
      { title: "SCANDAL ANTHEM", trackId: "08DchrgnFXBD6H142l4tvY", year: 2025 },
      { title: "You Like This B*tch - Choke Mix", trackId: "7fQJA4Amp6mcN7ftLmSgVc", year: 2024 },
    ],
    setTitle: "Gotec Club — 2h Hard Techno Set",
    setVenue: "Gotec Club",
    setYear: 2025,
    setYoutubeId: "NQNn7HGfMSk",
    trending: true,
    featured: true,
  }),
  // Peak-Time / Festival Techno
  entry(28, {
    slug: "alignment",
    name: "Alignment",
    country: "Italy",
    city: "Milan",
    scene: "Italy / Berlin",
    activeSince: 2016,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "0eNHvP3zBR2Qa0UfJN8c6O",
    labels: ["AnalyticTrail"],
    similarArtists: ["charlotte-de-witte", "amelie-lens", "funk-tribu"],
    trackSpecs: [
      { title: "Alignment", trackId: "50OKS8aOeuiegMnJuPKUeN", year: 2020 },
      { title: "System", trackId: "6R84ZlQF7gGkPB6o3GLZXB", year: 2022 },
      { title: "All Night", trackId: "2Y2Ydnk6XPTe4IpOTNs5Xh", year: 2023 },
    ],
    trending: true,
  }),
  entry(29, {
    slug: "999999999",
    name: "999999999",
    country: "Italy",
    city: "Venice",
    scene: "Italy",
    activeSince: 2016,
    genres: ["hard-techno", "acid-techno", "industrial-techno"],
    spotifyArtistId: "6uD2LjPHUjxrpax0se17Nc",
    labels: ["NineTimesNine"],
    similarArtists: ["alignment", "shlomo", "regal"],
    trackSpecs: [
      { title: "300000003", trackId: "34yR53qn56KlYXmhbuwjaa", year: 2018 },
      { title: "Hexadecimal", trackId: "1FubT3w22RMHC3vreAL7cH", year: 2020 },
      { title: "Live at Awakenings", trackId: "3kGr39dBiUUdFNw6iiLTDV", year: 2022 },
    ],
    featured: true,
    trending: true,
  }),
  entry(30, {
    slug: "shlomo",
    name: "Shlømo",
    country: "France",
    city: "Paris",
    scene: "Paris / Berlin",
    activeSince: 2015,
    genres: ["hard-techno", "industrial-techno"],
    spotifyArtistId: "0wN8XvAaWEWZQkY2Cl3rfQ",
    labels: ["Taapion"],
    similarArtists: ["alignment", "i-hate-models", "999999999"],
    trackSpecs: [
      { title: "One Mind", trackId: "2Y2Ydnk6XPTe4IpOTNs5Xh", year: 2020 },
      { title: "Datura", trackId: "6R84ZlQF7gGkPB6o3GLZXB", year: 2021 },
      { title: "Control Your Body", trackId: "50OKS8aOeuiegMnJuPKUeN", year: 2025 },
    ],
    trending: true,
    featured: true,
  }),
];

export const catalogArtists = catalogEntries.map(createCatalogArtist);
