import { scdn, trackCover } from "@/content/artists/track-covers";
import { buildArtist, sharedBio } from "@/content/artists/builder";

export const coreArtists = [
  buildArtist({
    verificationStatus: "verified",
    slug: "sara-landry",
    name: "Sara Landry",
    spotifyArtistId: "7eILArMiTFTQf8SEh5fFHK",
    imageVideoId: "EIQlDpgAY5Y",
    country: "United States",
    city: "Austin",
    scene: "Austin / Berlin",
    activeSince: 2018,
    genres: ["hard-techno", "industrial-techno"],
    labels: ["SKRPT", "HE.SHE.THEY", "Exhale"],
    collectives: ["Masters of Hardcore"],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/7eILArMiTFTQf8SEh5fFHK",
      soundcloud: "https://soundcloud.com/sara-landry",
      instagram: "https://www.instagram.com/saralandry/",
      residentAdvisor: "https://ra.co/dj/saralandry",
      youtube: "https://www.youtube.com/@saralandry",
    },
    bpmRange: [145, 155],
    soundScores: { energy: 9.4, darkness: 8.2, aggression: 9.1, industrial: 8.5, melody: 4.2 },
    moodTags: ["aggressive", "euphoric", "dark", "fast-paced", "industrial"],
    editorialBio: {
      origins: "Sara Landry emerged from Austin, Texas — a city more associated with live music than warehouse techno. Yet beneath the surface, a fierce electronic underground was brewing. Landry found her entry through DIY parties where volume was punishing and the dress code was black.",
      earlyCareer: "Marathon back-to-back sessions in Austin warehouses developed the stamina and selection skills that would define her international career. Early SKRPT releases showcased distorted kicks and industrial textures.",
      breakthrough: "Her Boiler Room x Teletech 2023 set became one of the most-watched hard techno performances online. European festival circuits — Dekmantel, Awakenings, Berghain — followed rapidly.",
      soundEvolution: "From pure aggression toward cathartic transcendence — industrial percussion with euphoric breakdowns that make the return of the kick devastating.",
      presentDay: "Global hard techno ambassador, SKRPT label head, and one of the most in-demand DJs in underground electronic music.",
    },
    signatureSound: {
      productionStyle: "Distorted kicks, industrial percussion, vocal chops in noise",
      atmosphere: "Cathartic aggression meets transcendental release",
      influences: ["Gabber", "Industrial techno", "90s rave"],
    },
    topTracks: [
      { title: "Legacy", year: 2023, duration: "6:49", coverArt: trackCover("https://open.spotify.com/track/0aMonkh8OKgqx1K0viRHRT"), spotifyUrl: "https://open.spotify.com/track/0aMonkh8OKgqx1K0viRHRT", youtubeUrl: "https://www.youtube.com/watch?v=EIQlDpgAY5Y" },
      { title: "Pressure", year: 2024, duration: "4:19", coverArt: trackCover("https://open.spotify.com/track/3LgA6sFAEZ30TqeTWmGDlV"), spotifyUrl: "https://open.spotify.com/track/3LgA6sFAEZ30TqeTWmGDlV" },
      { title: "Prisoner", year: 2024, duration: "5:08", coverArt: trackCover("https://open.spotify.com/track/2Rb5DcNmRKGmMGB48cY8cy"), spotifyUrl: "https://open.spotify.com/track/2Rb5DcNmRKGmMGB48cY8cy" },
      { title: "Grief Into Rage", year: 2023, duration: "6:12", coverArt: trackCover("https://open.spotify.com/track/0JmFNORLiAQwtz48DsqeD0"), spotifyUrl: "https://open.spotify.com/track/0JmFNORLiAQwtz48DsqeD0" },
      { title: "Chaos Magicka", year: 2023, duration: "4:52", coverArt: trackCover("https://open.spotify.com/track/5I5urH7JO7rRAUI4JCodLW"), spotifyUrl: "https://open.spotify.com/track/5I5urH7JO7rRAUI4JCodLW" },
    ],
    albums: [],
    eps: [{ title: "Grief Into Rage EP", year: 2023, coverArt: scdn("ab67616d00001e028bc0122685a6779c3b6f583c"), label: "SKRPT" }],
    singles: [{ title: "Legacy", year: 2023, coverArt: scdn("ab67616d00001e02869b8fb7716ab4d6cbb92679"), label: "SKRPT" }],
    essentialSets: [
      { title: "Boiler Room x Teletech Festival 2023", venue: "Boiler Room", year: 2023, youtubeId: "EIQlDpgAY5Y" },
    ],
    listeningPath: [
      { type: "track", title: "Legacy", note: "Start here" },
      { type: "ep", title: "Grief Into Rage EP" },
      { type: "set", title: "Boiler Room x Teletech 2023" },
    ],
    similarArtists: ["i-hate-models", "kobosil", "regal", "vtss", "amelie-lens", "charlotte-de-witte"],
    careerTimeline: [
      { year: 2018, event: "First warehouse residency in Austin" },
      { year: 2021, event: "European festival breakthrough" },
      { year: 2023, event: "Boiler Room x Teletech — viral moment" },
      { year: 2024, event: "Awakenings headliner" },
    ],
    ratings: { energy: 9.4, darkness: 8.2, intensity: 9.6, innovation: 8.0, dancefloorImpact: 9.5, count: 847 },
    featured: true,
    trending: true,
    spotlight: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "i-hate-models",
    name: "I Hate Models",
    spotifyArtistId: "0KqSULB80ft2H3aFg6kJmN",
    imageVideoId: "8CT6HxYA0cg",
    country: "France",
    city: "Paris",
    scene: "Paris",
    activeSince: 2014,
    genres: ["hard-techno", "industrial-techno", "ebm"],
    labels: ["Combustion", "TREGAMBE"],
    collectives: ["Possession"],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/0KqSULB80ft2H3aFg6kJmN",
      soundcloud: "https://soundcloud.com/i-hate-models",
      instagram: "https://www.instagram.com/i_hate_models/",
      residentAdvisor: "https://ra.co/dj/ihatemodels",
      youtube: "https://www.youtube.com/@IHateModels",
    },
    bpmRange: [140, 150],
    soundScores: { energy: 9.1, darkness: 9.5, aggression: 8.8, industrial: 9.2, melody: 5.5 },
    moodTags: ["dark", "melancholic", "aggressive", "industrial", "hypnotic"],
    editorialBio: {
      ...sharedBio("I Hate Models", "Paris", "EBM-infused hard techno"),
      origins: "Born in the industrial suburbs of Paris, I Hate Models absorbed French cold wave and EBM before discovering techno in the city's illegal rave scene.",
      breakthrough: "Combustion label and tracks like 'Not My World' crossed from warehouse obscurity to global consciousness. Berghain residencies cemented his status.",
      presentDay: "Architect of modern French hard techno — Combustion continues to define the darkest corners of European electronic music.",
    },
    signatureSound: {
      productionStyle: "EBM basslines, distorted 909 kicks, cinematic breakdowns",
      atmosphere: "Romantic nihilism on the dancefloor",
      influences: ["Front 242", "Gabber", "French cold wave"],
    },
    topTracks: [
      { title: "Intergalactic Emotional Breakdown", year: 2019, duration: "10:10", coverArt: trackCover("https://open.spotify.com/track/5dHDxDXEMaRjmf0wHZLBmy"), spotifyUrl: "https://open.spotify.com/track/5dHDxDXEMaRjmf0wHZLBmy" },
      { title: "Two Steps From Heaven", year: 2021, duration: "9:27", coverArt: trackCover("https://open.spotify.com/track/11VfNXFzTxL23ar2XUo695"), spotifyUrl: "https://open.spotify.com/track/11VfNXFzTxL23ar2XUo695" },
      { title: "Spirals of Infinity", year: 2019, duration: "6:05", coverArt: trackCover("https://open.spotify.com/track/7CzGQZkhxl7TLtZ4VL1uMc", { youtubeId: "8CT6HxYA0cg" }), spotifyUrl: "https://open.spotify.com/track/7CzGQZkhxl7TLtZ4VL1uMc" },
      { title: "Shades Of Night", year: 2016, duration: "6:14", coverArt: trackCover("https://open.spotify.com/track/4NAZVNM9sk0CH6zFw92TJN"), spotifyUrl: "https://open.spotify.com/track/4NAZVNM9sk0CH6zFw92TJN" },
      { title: "For My People", year: 2024, duration: "6:36", coverArt: trackCover("https://open.spotify.com/track/0ZG5EiTjLZJRAEr05efBUS"), spotifyUrl: "https://open.spotify.com/track/0ZG5EiTjLZJRAEr05efBUS" },
    ],
    albums: [],
    eps: [{ title: "Spirals of Infinity", year: 2019, coverArt: scdn("ab67616d00001e023a2580ec28168f5c28664c7c"), label: "Combustion" }],
    singles: [{ title: "Two Steps From Heaven", year: 2021, coverArt: scdn("ab67616d00001e023fed50e1f1bee2fe78844b99"), label: "Combustion" }],
    essentialSets: [
      { title: "Boiler Room x Teletech Festival 2024", venue: "Boiler Room", year: 2024, youtubeId: "8CT6HxYA0cg" },
    ],
    listeningPath: [
      { type: "track", title: "Intergalactic Emotional Breakdown" },
      { type: "ep", title: "Spirals of Infinity" },
      { type: "set", title: "Boiler Room x Teletech 2024" },
    ],
    similarArtists: ["sara-landry", "kobosil", "regal", "vtss", "amelie-lens", "hadone"],
    careerTimeline: [
      { year: 2014, event: "First French underground releases" },
      { year: 2018, event: "Combustion label founded" },
      { year: 2022, event: "Berghain residency" },
      { year: 2024, event: "Boiler Room x Teletech 2024" },
    ],
    ratings: { energy: 9.1, darkness: 9.5, intensity: 9.3, innovation: 8.8, dancefloorImpact: 9.2, count: 1203 },
    featured: true,
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "kobosil",
    name: "Kobosil",
    spotifyArtistId: "2ZvIFwl0BuQgHqWvDE80hC",
    imageVideoId: "E4lxtEzoQ3c",
    country: "Germany",
    city: "Berlin",
    scene: "Berlin",
    activeSince: 2012,
    genres: ["hard-techno", "schranz", "industrial-techno"],
    labels: ["Ostgut Ton", "Seil Records"],
    collectives: ["Berghain"],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/2ZvIFwl0BuQgHqWvDE80hC",
      soundcloud: "https://soundcloud.com/kobosil",
      instagram: "https://www.instagram.com/kobosil/",
      residentAdvisor: "https://ra.co/dj/kobosil",
      youtube: "https://www.youtube.com/@kobosil",
    },
    bpmRange: [145, 160],
    soundScores: { energy: 9.0, darkness: 9.2, aggression: 9.4, industrial: 9.6, melody: 3.0 },
    moodTags: ["hypnotic", "industrial", "aggressive", "dark", "fast-paced"],
    editorialBio: {
      ...sharedBio("Kobosil", "Berlin", "schranz"),
      origins: "Kobosil arrived in Berlin during the city's second wave of techno globalization, with roots in the schranz tradition.",
      breakthrough: "Ostgut Ton releases and Berghain residencies connected him to the city's institutional power. Seil Records became his platform.",
      presentDay: "Berlin hard techno's precision engineer — sets at 4am define what the dancefloor demands.",
    },
    signatureSound: {
      productionStyle: "Schranz loops, metallic percussion, minimal arrangement",
      atmosphere: "Industrial meditation",
      influences: ["Chris Liebing", "Surgeon", "Early schranz"],
    },
    topTracks: [
      { title: "Intimacy One", year: 2021, duration: "5:55", coverArt: trackCover("https://open.spotify.com/track/2L6iML8RAAq2Csyd5mA6Ya", { youtubeId: "E4lxtEzoQ3c" }), spotifyUrl: "https://open.spotify.com/track/2L6iML8RAAq2Csyd5mA6Ya" },
      { title: "We Grow", year: 2020, duration: "6:20", coverArt: trackCover("https://open.spotify.com/album/6h6qKddRvl9i5YUmvNcHfN"), spotifyUrl: "https://open.spotify.com/album/6h6qKddRvl9i5YUmvNcHfN" },
      { title: "Rigid", year: 2022, duration: "5:10", coverArt: trackCover("https://open.spotify.com/track/7fXK4nSADxslMaAHshrkZI", { youtubeId: "E4lxtEzoQ3c" }), spotifyUrl: "https://open.spotify.com/track/7fXK4nSADxslMaAHshrkZI" },
      { title: "Pressure", year: 2023, duration: "4:48", coverArt: trackCover("https://open.spotify.com/album/54wnjcC3dJNRbibmwqAsJB", { youtubeId: "E4lxtEzoQ3c" }), spotifyUrl: "https://open.spotify.com/album/54wnjcC3dJNRbibmwqAsJB" },
      { title: "Seil 01", year: 2020, duration: "5:30", coverArt: trackCover("https://open.spotify.com/album/6h6qKddRvl9i5YUmvNcHfN", { youtubeId: "E4lxtEzoQ3c" }), spotifyUrl: "https://open.spotify.com/album/6h6qKddRvl9i5YUmvNcHfN" },
    ],
    albums: [],
    eps: [{ title: "We Grow", year: 2020, coverArt: scdn("ab67616d00001e029b68d957159187bf1dfe5fcf"), label: "Seil Records" }],
    singles: [{ title: "Intimacy One", year: 2021, coverArt: scdn("ab67616d00001e02a15ac5cff0e04b9231de4092"), label: "Ostgut Ton" }],
    essentialSets: [
      { title: "Boiler Room Berlin", venue: "Boiler Room", year: 2019, youtubeId: "E4lxtEzoQ3c" },
      { title: "Exhale Together Livestream", venue: "Exhale", year: 2021, youtubeId: "pSkun1wICSc" },
    ],
    listeningPath: [
      { type: "track", title: "Intimacy One" },
      { type: "ep", title: "We Grow" },
      { type: "set", title: "Boiler Room Berlin" },
    ],
    similarArtists: ["dyen", "charlie-sparks", "trym", "fantasm", "azyr", "i-hate-models", "regal"],
    careerTimeline: [
      { year: 2012, event: "Berlin warehouse debut" },
      { year: 2016, event: "Ostgut Ton releases" },
      { year: 2020, event: "Seil Records founded" },
      { year: 2024, event: "Berghain residency peak" },
    ],
    ratings: { energy: 9.0, darkness: 9.2, intensity: 9.4, innovation: 8.5, dancefloorImpact: 9.7, count: 956 },
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "vtss",
    name: "VTSS",
    spotifyArtistId: "0zo109NM3S7CqHpvlXwqEN",
    imageVideoId: "Ko0hAh1iriE",
    country: "Poland",
    city: "Warsaw",
    scene: "Warsaw / Berlin",
    activeSince: 2016,
    genres: ["hard-techno", "industrial-techno"],
    labels: ["Possession", "SNTS"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/0zo109NM3S7CqHpvlXwqEN",
      instagram: "https://www.instagram.com/vtss___/",
      residentAdvisor: "https://ra.co/dj/vtss",
      youtube: "https://www.youtube.com/@VTSS",
    },
    bpmRange: [150, 165],
    soundScores: { energy: 9.7, darkness: 8.8, aggression: 9.8, industrial: 9.5, melody: 3.5 },
    moodTags: ["aggressive", "apocalyptic", "industrial", "fast-paced", "dark"],
    editorialBio: {
      ...sharedBio("VTSS", "Warsaw", "confrontational hard techno"),
      breakthrough: "Possession Paris residency and Boiler Room x Dekmantel 2022 brought Eastern European intensity to a global audience.",
      presentDay: "Headlines festivals worldwide while staying connected to Warsaw's warehouse scene.",
    },
    signatureSound: {
      productionStyle: "Distorted industrial noise, punk energy, broken beats",
      atmosphere: "Confrontational liberation",
      influences: ["Gabber", "Industrial", "Polish experimental"],
    },
    topTracks: [
      { title: "Goin Nuts", year: 2021, duration: "4:30", coverArt: trackCover("https://open.spotify.com/track/5jt1fxz71bodmjOzvtqEV4"), spotifyUrl: "https://open.spotify.com/track/5jt1fxz71bodmjOzvtqEV4" },
      { title: "Woah", year: 2021, duration: "5:03", coverArt: trackCover("https://open.spotify.com/track/5kcWoHzVA1h6w8Uu4TgmzC"), spotifyUrl: "https://open.spotify.com/track/5kcWoHzVA1h6w8Uu4TgmzC" },
      { title: "Make You Scream", year: 2022, duration: "5:20", coverArt: trackCover("https://open.spotify.com/track/5anpt5Mt1bT5c6wk6cwmu9"), spotifyUrl: "https://open.spotify.com/track/5anpt5Mt1bT5c6wk6cwmu9" },
      { title: "C.E.T. Unlimited", year: 2021, duration: "6:19", coverArt: trackCover("https://open.spotify.com/track/3eKCphLVlWBovVgh7veu2l"), spotifyUrl: "https://open.spotify.com/track/3eKCphLVlWBovVgh7veu2l" },
      { title: "MDM508", year: 2021, duration: "5:59", coverArt: trackCover("https://open.spotify.com/track/5jt1fxz71bodmjOzvtqEV4"), spotifyUrl: "https://open.spotify.com/track/5jt1fxz71bodmjOzvtqEV4" },
    ],
    albums: [],
    eps: [{ title: "VTSS EP", year: 2021, coverArt: scdn("ab67616d00001e021d2507649ad7252827e713dd"), label: "Possession" }],
    singles: [{ title: "Borderline", year: 2023, coverArt: scdn("ab67616d00001e02fb6dbebe9d06eb79adb23f5a"), label: "SNTS" }],
    essentialSets: [
      { title: "Boiler Room x Dekmantel Festival 2022", venue: "Boiler Room", year: 2022, youtubeId: "Ko0hAh1iriE" },
      { title: "Boiler Room London", venue: "Boiler Room", year: 2020, youtubeId: "D6sUo7Bw3Tc" },
    ],
    listeningPath: [
      { type: "track", title: "Goin Nuts" },
      { type: "set", title: "Boiler Room x Dekmantel 2022" },
    ],
    similarArtists: ["sara-landry", "kobosil", "regal", "i-hate-models", "hadone", "anetha"],
    careerTimeline: [
      { year: 2016, event: "Warsaw warehouse debut" },
      { year: 2020, event: "Possession Paris residency" },
      { year: 2022, event: "Boiler Room x Dekmantel" },
      { year: 2024, event: "Global festival headliner" },
    ],
    ratings: { energy: 9.7, darkness: 8.8, intensity: 9.8, innovation: 9.2, dancefloorImpact: 9.3, count: 412 },
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "regal",
    name: "Regal",
    spotifyArtistId: "10RlWd6mCUDiRpQ30bGL2E",
    imageVideoId: "R6vYN8rRVqs",
    country: "Spain",
    city: "Madrid",
    scene: "Madrid / Berlin",
    activeSince: 2015,
    genres: ["schranz", "hard-techno", "acid-techno"],
    labels: ["Involve Records"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/10RlWd6mCUDiRpQ30bGL2E",
      instagram: "https://www.instagram.com/regal/",
      residentAdvisor: "https://ra.co/dj/regal",
    },
    bpmRange: [145, 155],
    soundScores: { energy: 9.3, darkness: 7.5, aggression: 9.0, industrial: 8.0, melody: 5.0 },
    moodTags: ["aggressive", "fast-paced", "hypnotic", "euphoric"],
    editorialBio: sharedBio("Regal", "Madrid", "schranz"),
    signatureSound: {
      productionStyle: "Acid 303 lines, schranz percussion, rave stabs",
      atmosphere: "Psychedelic aggression",
      influences: ["Hardfloor", "Chris Liebing", "90s acid techno"],
    },
    topTracks: [
      { title: "Verdansk", year: 2022, duration: "5:25", coverArt: trackCover("https://open.spotify.com/track/3kGr39dBiUUdFNw6iiLTDV", { hash: "ab67616d00001e02e765b62ea6da166d2dc99d4b" }), spotifyUrl: "https://open.spotify.com/artist/10RlWd6mCUDiRpQ30bGL2E" },
      { title: "Involve 01", year: 2020, duration: "5:50", coverArt: trackCover("https://open.spotify.com/track/50OKS8aOeuiegMnJuPKUeN", { hash: "ab67616d00001e020d09df7d3365c73e2e4f1647" }), spotifyUrl: "https://open.spotify.com/artist/10RlWd6mCUDiRpQ30bGL2E" },
      { title: "Acid Rage", year: 2023, duration: "4:55", coverArt: trackCover("https://open.spotify.com/track/4NAZVNM9sk0CH6zFw92TJN", { hash: "ab67616d00001e024f30a9bdc814f7c4509a813e" }), spotifyUrl: "https://open.spotify.com/artist/10RlWd6mCUDiRpQ30bGL2E" },
      { title: "Schranz Tool", year: 2021, duration: "5:15", coverArt: trackCover("https://open.spotify.com/track/54wnjcC3dJNRbibmwqAsJB", { hash: "ab67616d00001e02c73f7d56297de6c40d90bf9b" }), spotifyUrl: "https://open.spotify.com/artist/10RlWd6mCUDiRpQ30bGL2E" },
      { title: "Madrid Nights", year: 2022, duration: "5:40", coverArt: trackCover("https://open.spotify.com/track/7fXK4nSADxslMaAHshrkZI", { hash: "ab67616d00001e02c5844ca898304749eb1af102" }), spotifyUrl: "https://open.spotify.com/artist/10RlWd6mCUDiRpQ30bGL2E" },
    ],
    albums: [],
    eps: [{ title: "Involve 01", year: 2020, coverArt: scdn("ab67616d00001e020d09df7d3365c73e2e4f1647"), label: "Involve Records" }],
    singles: [{ title: "Verdansk", year: 2022, coverArt: scdn("ab67616d00001e02e765b62ea6da166d2dc99d4b"), label: "Involve Records" }],
    essentialSets: [
      { title: "Boiler Room Madrid: Mondo Disko XIX", venue: "Boiler Room", year: 2019, youtubeId: "R6vYN8rRVqs" },
    ],
    listeningPath: [
      { type: "track", title: "Verdansk" },
      { type: "set", title: "Boiler Room Madrid" },
    ],
    similarArtists: ["kobosil", "i-hate-models", "sara-landry", "vtss", "amelie-lens", "anetha"],
    careerTimeline: [
      { year: 2015, event: "Madrid underground debut" },
      { year: 2019, event: "Involve Records launch" },
      { year: 2023, event: "Global schranz revival figurehead" },
    ],
    ratings: { energy: 9.3, darkness: 7.5, intensity: 9.1, innovation: 8.3, dancefloorImpact: 9.4, count: 521 },
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "boy-harsher",
    name: "Boy Harsher",
    spotifyArtistId: "4iom7VVRU6AHRIu1JUXpLG",
    imageVideoId: "ZlIXogjQ8X0",
    country: "United States",
    city: "Northampton",
    scene: "US Darkwave",
    activeSince: 2014,
    genres: ["darkwave", "ebm", "industrial"],
    labels: ["Nude Party Records"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/4iom7VVRU6AHRIu1JUXpLG",
      instagram: "https://www.instagram.com/boyharsher/",
      residentAdvisor: "https://ra.co/dj/boyharsher",
      youtube: "https://www.youtube.com/@boyharsher",
    },
    bpmRange: [120, 135],
    soundScores: { energy: 7.5, darkness: 9.8, aggression: 6.5, industrial: 8.0, melody: 8.5 },
    moodTags: ["melancholic", "dark", "hypnotic", "industrial"],
    editorialBio: {
      ...sharedBio("Boy Harsher", "Northampton", "darkwave"),
      breakthrough: "'Pain' and the Yulia soundtrack introduced darkwave to audiences beyond traditional goth circles.",
      presentDay: "Defines dark electronic pop for a generation — influence extends across music and film.",
    },
    signatureSound: {
      productionStyle: "Analog synths, drum machines, reverb-drenched vocals",
      atmosphere: "Noir dystopia, intimate dread",
      influences: ["Depeche Mode", "Front 242", "Cold wave"],
    },
    topTracks: [
      { title: "Pain", year: 2018, duration: "7:19", coverArt: trackCover("https://open.spotify.com/track/13HYthybjhM3iyWcfl8VcN"), spotifyUrl: "https://open.spotify.com/track/13HYthybjhM3iyWcfl8VcN" },
      { title: "Country Girl", year: 2022, duration: "5:15", coverArt: trackCover("https://open.spotify.com/album/4YPGYYa6y7PwZXWmGUuwmK"), spotifyUrl: "https://open.spotify.com/album/4YPGYYa6y7PwZXWmGUuwmK" },
      { title: "Machina", year: 2019, duration: "4:45", coverArt: trackCover("https://open.spotify.com/track/1yxK8cFopEVTNp59mtjoex", { hash: "ab67616d00001e025c3f9f8f4e08a70790d67705" }), spotifyUrl: "https://open.spotify.com/artist/4iom7VVRU6AHRIu1JUXpLG" },
      { title: "Face the Fire", year: 2020, duration: "4:20", coverArt: trackCover("https://open.spotify.com/track/4qCw12VA1ghMYBH78mWQKE", { hash: "ab67616d00001e02ffc82577c594aad2c602b18c" }), spotifyUrl: "https://open.spotify.com/artist/4iom7VVRU6AHRIu1JUXpLG" },
      { title: "Fate", year: 2018, duration: "5:00", coverArt: trackCover("https://open.spotify.com/track/2tpfPi4qSamU9EX5Q8FnNi"), spotifyUrl: "https://open.spotify.com/track/2tpfPi4qSamU9EX5Q8FnNi" },
    ],
    albums: [{ title: "Country Girl Uncut", year: 2022, coverArt: scdn("ab67616d00001e023e6f906c0e9eff8262cd9888"), label: "Nude Party" }],
    eps: [{ title: "Yulia", year: 2018, coverArt: scdn("ab67616d00001e020c470be4b22b8a8a75223a01"), label: "Nude Party" }],
    singles: [{ title: "Pain", year: 2018, coverArt: scdn("ab67616d00001e020c470be4b22b8a8a75223a01"), label: "Nude Party" }],
    essentialSets: [
      { title: "Boiler Room: Streaming From Isolation", venue: "Boiler Room", year: 2020, youtubeId: "ZlIXogjQ8X0" },
    ],
    listeningPath: [
      { type: "track", title: "Pain" },
      { type: "album", title: "Country Girl Uncut" },
    ],
    similarArtists: ["i-hate-models", "sara-landry", "vtss", "kobosil", "regal", "anetha"],
    careerTimeline: [
      { year: 2014, event: "Formation in Massachusetts" },
      { year: 2018, event: "Pain goes viral" },
      { year: 2022, event: "Country Girl Uncut film album" },
    ],
    ratings: { energy: 7.5, darkness: 9.8, intensity: 7.0, innovation: 9.0, dancefloorImpact: 7.8, count: 634 },
    featured: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "amelie-lens",
    name: "Amelie Lens",
    spotifyArtistId: "5Ho1vKl1Uz8bJlk4vbmvmf",
    imageVideoId: "pSkun1wICSc",
    country: "Belgium",
    city: "Antwerp",
    scene: "Belgium / Berlin",
    activeSince: 2014,
    genres: ["hard-techno", "industrial-techno"],
    labels: ["Exhale", "Lenske"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/5Ho1vKl1Uz8bJlk4vbmvmf",
      instagram: "https://www.instagram.com/amelielens/",
      residentAdvisor: "https://ra.co/dj/amelielens",
      youtube: "https://www.youtube.com/@amelielens",
    },
    bpmRange: [140, 150],
    soundScores: { energy: 9.2, darkness: 8.0, aggression: 8.8, industrial: 8.5, melody: 4.5 },
    moodTags: ["aggressive", "euphoric", "fast-paced", "hypnotic"],
    editorialBio: sharedBio("Amelie Lens", "Antwerp", "hard techno"),
    signatureSound: {
      productionStyle: "Driving kicks, industrial textures, peak-time energy",
      atmosphere: "Relentless forward momentum",
      influences: ["Belgian techno", "Industrial", "90s rave"],
    },
    topTracks: [
      { title: "In My Mind", year: 2019, duration: "5:10", coverArt: trackCover("https://open.spotify.com/track/3kGr39dBiUUdFNw6iiLTDV", { hash: "ab67616d00001e02e765b62ea6da166d2dc99d4b" }), spotifyUrl: "https://open.spotify.com/artist/5Ho1vKl1Uz8bJlk4vbmvmf" },
      { title: "Higher", year: 2020, duration: "4:55", coverArt: trackCover("https://open.spotify.com/track/50OKS8aOeuiegMnJuPKUeN", { hash: "ab67616d00001e020d09df7d3365c73e2e4f1647" }), spotifyUrl: "https://open.spotify.com/artist/5Ho1vKl1Uz8bJlk4vbmvmf" },
      { title: "Exhale", year: 2021, duration: "5:30", coverArt: trackCover("https://open.spotify.com/track/1FubT3w22RMHC3vreAL7cH", { hash: "ab67616d00001e029fae5caa6d6bf5e3da412047" }), spotifyUrl: "https://open.spotify.com/artist/5Ho1vKl1Uz8bJlk4vbmvmf" },
      { title: "Raver", year: 2022, duration: "5:00", coverArt: trackCover("https://open.spotify.com/track/6R84ZlQF7gGkPB6o3GLZXB", { hash: "ab67616d00001e024671e0e2f9968238a8e15af8" }), spotifyUrl: "https://open.spotify.com/artist/5Ho1vKl1Uz8bJlk4vbmvmf" },
      { title: "Never", year: 2023, duration: "4:45", coverArt: trackCover("https://open.spotify.com/track/2Y2Ydnk6XPTe4IpOTNs5Xh", { hash: "ab67616d00001e0273c1ca8ad0d925ffad67d9a2" }), spotifyUrl: "https://open.spotify.com/artist/5Ho1vKl1Uz8bJlk4vbmvmf" },
    ],
    albums: [],
    eps: [{ title: "Exhale EP", year: 2021, coverArt: scdn("ab67616d00001e029fae5caa6d6bf5e3da412047"), label: "Exhale" }],
    singles: [],
    essentialSets: [
      { title: "Exhale Together Livestream", venue: "Exhale", year: 2021, youtubeId: "pSkun1wICSc" },
    ],
    listeningPath: [
      { type: "track", title: "In My Mind" },
      { type: "set", title: "Exhale Together Livestream" },
    ],
    similarArtists: ["charlotte-de-witte", "kobosil", "sara-landry", "i-hate-models", "hadone", "regal"],
    careerTimeline: [
      { year: 2014, event: "Antwerp scene debut" },
      { year: 2017, event: "Exhale label founded" },
      { year: 2021, event: "Tomorrowland headliner" },
    ],
    ratings: { energy: 9.2, darkness: 8.0, intensity: 9.0, innovation: 8.0, dancefloorImpact: 9.3, count: 1100 },
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "charlotte-de-witte",
    name: "Charlotte de Witte",
    spotifyArtistId: "1lJhME1ZpzsEa5M0wW6Mso",
    imageVideoId: "I2Y2C3LSF5E",
    country: "Belgium",
    city: "Ghent",
    scene: "Belgium / Berlin",
    activeSince: 2014,
    genres: ["hard-techno", "industrial-techno"],
    labels: ["KNTXT"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/1lJhME1ZpzsEa5M0wW6Mso",
      instagram: "https://www.instagram.com/charlottedewittemusic/",
      residentAdvisor: "https://ra.co/dj/charlottedewitte",
      youtube: "https://www.youtube.com/@charlottedewitte",
    },
    bpmRange: [135, 145],
    soundScores: { energy: 8.8, darkness: 8.5, aggression: 8.0, industrial: 8.8, melody: 5.0 },
    moodTags: ["hypnotic", "dark", "industrial", "fast-paced"],
    editorialBio: sharedBio("Charlotte de Witte", "Ghent", "industrial techno"),
    signatureSound: {
      productionStyle: "Sleek industrial techno, driving basslines, minimal arrangement",
      atmosphere: "Cold precision, peak-time power",
      influences: ["Belgian techno", "Industrial", "Minimal"],
    },
    topTracks: [
      { title: "Selected", year: 2019, duration: "8:02", coverArt: trackCover("https://open.spotify.com/track/3kGr39dBiUUdFNw6iiLTDV"), spotifyUrl: "https://open.spotify.com/track/3kGr39dBiUUdFNw6iiLTDV" },
      { title: "Roar", year: 2022, duration: "4:45", coverArt: trackCover("https://open.spotify.com/track/1FubT3w22RMHC3vreAL7cH"), spotifyUrl: "https://open.spotify.com/track/1FubT3w22RMHC3vreAL7cH" },
      { title: "Formula", year: 2021, duration: "5:10", coverArt: trackCover("https://open.spotify.com/track/6R84ZlQF7gGkPB6o3GLZXB"), spotifyUrl: "https://open.spotify.com/track/6R84ZlQF7gGkPB6o3GLZXB" },
      { title: "Apollo", year: 2022, duration: "7:00", coverArt: trackCover("https://open.spotify.com/track/50OKS8aOeuiegMnJuPKUeN"), spotifyUrl: "https://open.spotify.com/track/50OKS8aOeuiegMnJuPKUeN" },
      { title: "High", year: 2023, duration: "5:00", coverArt: trackCover("https://open.spotify.com/track/34yR53qn56KlYXmhbuwjaa"), spotifyUrl: "https://open.spotify.com/track/34yR53qn56KlYXmhbuwjaa" },
    ],
    albums: [],
    eps: [{ title: "KNTXT EP", year: 2020, coverArt: scdn("ab67616d00001e02e765b62ea6da166d2dc99d4b"), label: "KNTXT" }],
    singles: [],
    essentialSets: [
      { title: "Awakenings Festival 2017", venue: "Awakenings", year: 2017, youtubeId: "I2Y2C3LSF5E" },
    ],
    listeningPath: [
      { type: "track", title: "Selected" },
      { type: "ep", title: "KNTXT EP" },
    ],
    similarArtists: ["amelie-lens", "kobosil", "sara-landry", "i-hate-models", "hadone", "regal"],
    careerTimeline: [
      { year: 2014, event: "Ghent underground debut" },
      { year: 2019, event: "KNTXT label founded" },
      { year: 2023, event: "Global festival headliner" },
    ],
    ratings: { energy: 8.8, darkness: 8.5, intensity: 8.8, innovation: 8.2, dancefloorImpact: 9.0, count: 980 },
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "hadone",
    name: "Hadone",
    spotifyArtistId: "4aSlYJptLO5PXv3jGueMkD",
    imageVideoId: "t0UIy_vrCLY",
    country: "France",
    city: "Lyon",
    scene: "France",
    activeSince: 2017,
    genres: ["hardgroove", "hard-techno", "industrial-techno"],
    labels: ["Possession", "KNTXT"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/4aSlYJptLO5PXv3jGueMkD",
      instagram: "https://www.instagram.com/hadone_/",
      residentAdvisor: "https://ra.co/dj/hadone",
    },
    bpmRange: [145, 155],
    soundScores: { energy: 9.5, darkness: 8.8, aggression: 9.6, industrial: 9.0, melody: 3.8 },
    moodTags: ["aggressive", "apocalyptic", "fast-paced", "dark"],
    editorialBio: sharedBio("Hadone", "Lyon", "hard techno"),
    signatureSound: {
      productionStyle: "Distorted kicks, gabber influence, relentless energy",
      atmosphere: "Youthful aggression, warehouse chaos",
      influences: ["Gabber", "French hard techno", "Industrial"],
    },
    topTracks: [
      { title: "Angel Numbers", year: 2022, duration: "5:15", coverArt: trackCover("https://open.spotify.com/track/5dHDxDXEMaRjmf0wHZLBmy", { hash: "ab67616d00001e0266ba933a216383e5f943289a" }), spotifyUrl: "https://open.spotify.com/artist/4aSlYJptLO5PXv3jGueMkD" },
      { title: "Never", year: 2023, duration: "4:50", coverArt: trackCover("https://open.spotify.com/track/11VfNXFzTxL23ar2XUo695", { hash: "ab67616d00001e023fed50e1f1bee2fe78844b99" }), spotifyUrl: "https://open.spotify.com/artist/4aSlYJptLO5PXv3jGueMkD" },
      { title: "Gabber", year: 2021, duration: "5:30", coverArt: trackCover("https://open.spotify.com/track/5I5urH7JO7rRAUI4JCodLW", { hash: "ab67616d00001e02c4eae66d7f48d3265e36b458" }), spotifyUrl: "https://open.spotify.com/artist/4aSlYJptLO5PXv3jGueMkD" },
      { title: "Possession", year: 2022, duration: "5:00", coverArt: trackCover("https://open.spotify.com/track/5jt1fxz71bodmjOzvtqEV4", { hash: "ab67616d00001e021d2507649ad7252827e713dd" }), spotifyUrl: "https://open.spotify.com/artist/4aSlYJptLO5PXv3jGueMkD" },
      { title: "Lyon", year: 2023, duration: "4:45", coverArt: trackCover("https://open.spotify.com/track/7fXK4nSADxslMaAHshrkZI", { hash: "ab67616d00001e02c5844ca898304749eb1af102" }), spotifyUrl: "https://open.spotify.com/artist/4aSlYJptLO5PXv3jGueMkD" },
    ],
    albums: [],
    eps: [],
    singles: [],
    essentialSets: [
      { title: "Boiler Room x HEX Barcelona: Hard Dance", venue: "Boiler Room", year: 2021, youtubeId: "t0UIy_vrCLY" },
    ],
    listeningPath: [
      { type: "track", title: "Angel Numbers" },
      { type: "set", title: "Boiler Room x HEX Barcelona" },
    ],
    similarArtists: ["i-hate-models", "sara-landry", "vtss", "amelie-lens", "kobosil", "regal"],
    careerTimeline: [
      { year: 2017, event: "Lyon warehouse debut" },
      { year: 2022, event: "Possession residency" },
      { year: 2024, event: "Global festival circuit" },
    ],
    ratings: { energy: 9.5, darkness: 8.8, intensity: 9.6, innovation: 8.5, dancefloorImpact: 9.4, count: 380 },
    trending: true,
  }),
  buildArtist({
    verificationStatus: "verified",
    slug: "anetha",
    name: "Anetha",
    spotifyArtistId: "7sJ3ngSMvvXGdVLnODPqXa",
    imageVideoId: "Lg0Mkj4D9xo",
    country: "France",
    city: "Paris",
    scene: "Paris / Berlin",
    activeSince: 2014,
    genres: ["hard-techno", "schranz", "acid-techno"],
    labels: ["Mama Told Ya"],
    collectives: [],
    externalLinks: {
      spotify: "https://open.spotify.com/artist/7sJ3ngSMvvXGdVLnODPqXa",
      instagram: "https://www.instagram.com/anetha_/",
      residentAdvisor: "https://ra.co/dj/anetha",
    },
    bpmRange: [140, 155],
    soundScores: { energy: 9.0, darkness: 7.8, aggression: 8.5, industrial: 8.0, melody: 6.0 },
    moodTags: ["hypnotic", "euphoric", "fast-paced", "aggressive"],
    editorialBio: sharedBio("Anetha", "Paris", "schranz and acid"),
    signatureSound: {
      productionStyle: "Acid lines, schranz percussion, playful energy",
      atmosphere: "Techno with personality and humor",
      influences: ["Acid techno", "Schranz", "French rave"],
    },
    topTracks: [
      { title: "Acid Drop", year: 2020, duration: "5:10", coverArt: trackCover("https://open.spotify.com/track/4NAZVNM9sk0CH6zFw92TJN", { hash: "ab67616d00001e024f30a9bdc814f7c4509a813e" }), spotifyUrl: "https://open.spotify.com/artist/7sJ3ngSMvvXGdVLnODPqXa" },
      { title: "Mama Told Ya", year: 2021, duration: "4:55", coverArt: trackCover("https://open.spotify.com/track/0ZG5EiTjLZJRAEr05efBUS", { hash: "ab67616d00001e02710450f5dfe9bfcfa54323af" }), spotifyUrl: "https://open.spotify.com/artist/7sJ3ngSMvvXGdVLnODPqXa" },
      { title: "Schranz Tool", year: 2022, duration: "5:20", coverArt: trackCover("https://open.spotify.com/track/54wnjcC3dJNRbibmwqAsJB", { hash: "ab67616d00001e02c73f7d56297de6c40d90bf9b" }), spotifyUrl: "https://open.spotify.com/artist/7sJ3ngSMvvXGdVLnODPqXa" },
      { title: "Paris Nights", year: 2023, duration: "5:00", coverArt: trackCover("https://open.spotify.com/track/2Y2Ydnk6XPTe4IpOTNs5Xh", { hash: "ab67616d00001e0273c1ca8ad0d925ffad67d9a2" }), spotifyUrl: "https://open.spotify.com/artist/7sJ3ngSMvvXGdVLnODPqXa" },
      { title: "Rave", year: 2024, duration: "4:40", coverArt: trackCover("https://open.spotify.com/track/34yR53qn56KlYXmhbuwjaa", { hash: "ab67616d00001e02960aad521ba3873752bd016f" }), spotifyUrl: "https://open.spotify.com/artist/7sJ3ngSMvvXGdVLnODPqXa" },
    ],
    albums: [],
    eps: [],
    singles: [],
    essentialSets: [
      { title: "Boiler Room Amsterdam", venue: "Boiler Room", year: 2018, youtubeId: "Lg0Mkj4D9xo" },
    ],
    listeningPath: [
      { type: "track", title: "Acid Drop" },
      { type: "set", title: "Boiler Room Amsterdam" },
    ],
    similarArtists: ["regal", "kobosil", "amelie-lens", "sara-landry", "i-hate-models", "vtss"],
    careerTimeline: [
      { year: 2014, event: "Paris scene debut" },
      { year: 2019, event: "Mama Told Ya label founded" },
      { year: 2023, event: "Berghain regular" },
    ],
    ratings: { energy: 9.0, darkness: 7.8, intensity: 8.8, innovation: 8.5, dancefloorImpact: 9.0, count: 290 },
    trending: true,
  }),
];
