/**
 * AUTO-GENERATED by scripts/ingest-hor-berlin-archive.ts
 * Verified HÖR Berlin artists not previously in the catalog.
 * Do not edit by hand — re-run the ingest script.
 */
import type { Genre } from "@/types";
import { createCatalogArtist, type CatalogEntry } from "./builder";

interface HorSeed {
  slug: string;
  name: string;
  country: string;
  city: string;
  activeSince: number;
  genres: Genre[];
  labels: string[];
  similarArtists: string[];
  spotifyArtistId: string;
}

const SEEDS: HorSeed[] = [

];

function toEntry(idx: number, seed: HorSeed): CatalogEntry {
  return {
    slug: seed.slug,
    name: seed.name,
    country: seed.country,
    city: seed.city,
    scene: seed.city,
    activeSince: seed.activeSince,
    genres: seed.genres,
    verificationStatus: "partial",
    spotifyArtistId: seed.spotifyArtistId,
    labels: seed.labels,
    bpmRange: [140, 155],
    similarArtists: seed.similarArtists,
    tracks: [],
  };
}

export const horBerlinCatalogArtists = SEEDS.map((seed, i) =>
  createCatalogArtist(toEntry(i + 900, seed)),
);
