import type { VerifiedImageRecord } from "@/lib/archive/images/types";

/** Verified Spotify artist IDs from deep portrait research (June 2026). */
export const VERIFIED_SPOTIFY_ARTIST_IDS: Record<string, string> = {
  "paula-temple": "4iy2RFU8gIpXF5yaK0l8ZT",
  perc: "4iyqyvWXO734GUNLTTnrPQ",
  "ancient-methods": "2kWRgcJHbgSEAIgewkJ1g2",
  surgeon: "1PSylklb2w06BAAHEtepqM",
  "adam-x": "4puKiwP3DNIzEaxPCheUbj",
  "sven-wittekind": "1Xoao0EbCROD5MzC3iyyAD",
  lucy: "0BlPI3UKzTcN2jf0gCa0b9",
  "josh-wink": "6DQLkRykAsF6paJnlIMX4H",
  "assemblage-23": "7pwThElmrxl0pjTwXMojCx",
  "she-past-away": "6paE8ghTau4qwwNzVRSgjR",
  "lebanon-hanover": "6w8h2uD28BEdg7bX4k3Lh7",
  "drab-majesty": "2CSEKlTT9empsZ8vZWsrKO",
  "the-soft-moon": "40HeNm05FEAxGx8gUOV4my",
  rrose: "5naKaYAyzzuPDsh4H2dwyT",
  blawan: "64kN9EkSTHYhda2FupL0KI",
  ph87: "6w8j7obDDze1ovIL3lXGZf",
  "part-time-killer": "1PDjdSn9YCXz1reA1PUcC0",
  "victor-ruiz": "0xgdNNa5mIbnJKp8AG8S4z",
  "dave-the-drummer": "4ulxN8QnUlk3bX6IopQO7C",
  "paranoid-london": "0KyUH5WmspOhuIQAnw42Fb",
  randomer: "7K0WJzyqUNRhraNcsvJp1h",
  "front-242": "2tyMOS8xKREgpEwHnLc6EX",
  norbak: "0TwXWZcwzGVVOa1Vdu3UEj",
  "mcr-t": "4m7q9onIm2bqhwHy9utqmw",
  "hector-oaks": "2FZAQdFEANNv5Gi29PI10x",
  ansome: "14gRo11WOeTXBDcgFr8Ejb",
  "alex-bau": "0NepOrVsrboBKYECeSmwak",
  deepbass: "4JBXPj21sTqOZvgQurUJoP",
  petduo: "5SEUYqumyvmrkgWpOco1lo",
  lft: "0CxkG7EdCzA4QJoDeiODFP",
  hante: "5PhSiNjHZevtfAj9zmvVkU",
  weichentechnikk: "3sIkF6FOnvaaA9nLCnITrh",
  "petra-flurr": "51exL0KZS30QQSJd9osmig",
  rumina: "7IDiYtKojSbRAaf2b2Mpew",
};

type ResearchSource = "spotify-official" | "resident-advisor";

interface ResearchedPortraitSeed {
  slug: string;
  artistName: string;
  source: ResearchSource;
  sourceUrl: string;
  sourceType: VerifiedImageRecord["sourceType"];
  attribution: string;
  spotifyArtistId?: string;
}

const RESEARCHED_PORTRAIT_SEEDS: ResearchedPortraitSeed[] = [
  {
    slug: "paula-temple",
    artistName: "Paula Temple",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/4iy2RFU8gIpXF5yaK0l8ZT",
    sourceType: "spotify",
    attribution: "Spotify — Paula Temple official artist photo",
    spotifyArtistId: "4iy2RFU8gIpXF5yaK0l8ZT",
  },
  {
    slug: "perc",
    artistName: "Perc",
    source: "resident-advisor",
    sourceUrl: "https://ra.co/dj/perc",
    sourceType: "resident-advisor",
    attribution: "Resident Advisor — Perc (Ali Wells) official profile photo",
    spotifyArtistId: "4iyqyvWXO734GUNLTTnrPQ",
  },
  {
    slug: "ancient-methods",
    artistName: "Ancient Methods",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/2kWRgcJHbgSEAIgewkJ1g2",
    sourceType: "spotify",
    attribution: "Spotify — Ancient Methods official artist photo",
    spotifyArtistId: "2kWRgcJHbgSEAIgewkJ1g2",
  },
  {
    slug: "surgeon",
    artistName: "Surgeon",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/1PSylklb2w06BAAHEtepqM",
    sourceType: "spotify",
    attribution: "Spotify — Surgeon (Anthony Child) official artist photo",
    spotifyArtistId: "1PSylklb2w06BAAHEtepqM",
  },
  {
    slug: "adam-x",
    artistName: "Adam X",
    source: "resident-advisor",
    sourceUrl: "https://ra.co/dj/adamx",
    sourceType: "resident-advisor",
    attribution: "Resident Advisor — Adam X official profile photo",
    spotifyArtistId: "4puKiwP3DNIzEaxPCheUbj",
  },
  {
    slug: "sven-wittekind",
    artistName: "Sven Wittekind",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/1Xoao0EbCROD5MzC3iyyAD",
    sourceType: "spotify",
    attribution: "Spotify — Sven Wittekind official artist photo",
    spotifyArtistId: "1Xoao0EbCROD5MzC3iyyAD",
  },
  {
    slug: "assemblage-23",
    artistName: "Assemblage 23",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/7pwThElmrxl0pjTwXMojCx",
    sourceType: "spotify",
    attribution: "Spotify — Assemblage 23 official artist photo",
    spotifyArtistId: "7pwThElmrxl0pjTwXMojCx",
  },
  {
    slug: "she-past-away",
    artistName: "She Past Away",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/6paE8ghTau4qwwNzVRSgjR",
    sourceType: "spotify",
    attribution: "Spotify — She Past Away official artist photo",
    spotifyArtistId: "6paE8ghTau4qwwNzVRSgjR",
  },
  {
    slug: "lebanon-hanover",
    artistName: "Lebanon Hanover",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/6w8h2uD28BEdg7bX4k3Lh7",
    sourceType: "spotify",
    attribution: "Spotify — Lebanon Hanover official artist photo",
    spotifyArtistId: "6w8h2uD28BEdg7bX4k3Lh7",
  },
  {
    slug: "drab-majesty",
    artistName: "Drab Majesty",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/2CSEKlTT9empsZ8vZWsrKO",
    sourceType: "spotify",
    attribution: "Spotify — Drab Majesty official artist photo",
    spotifyArtistId: "2CSEKlTT9empsZ8vZWsrKO",
  },
  {
    slug: "the-soft-moon",
    artistName: "The Soft Moon",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/40HeNm05FEAxGx8gUOV4my",
    sourceType: "spotify",
    attribution: "Spotify — The Soft Moon official artist photo",
    spotifyArtistId: "40HeNm05FEAxGx8gUOV4my",
  },
  {
    slug: "rrose",
    artistName: "Rrose",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/5naKaYAyzzuPDsh4H2dwyT",
    sourceType: "spotify",
    attribution: "Spotify — Rrose official artist photo",
    spotifyArtistId: "5naKaYAyzzuPDsh4H2dwyT",
  },
  {
    slug: "blawan",
    artistName: "Blawan",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/64kN9EkSTHYhda2FupL0KI",
    sourceType: "spotify",
    attribution: "Spotify — Blawan official artist photo",
    spotifyArtistId: "64kN9EkSTHYhda2FupL0KI",
  },
  {
    slug: "ph87",
    artistName: "PH87",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/6w8j7obDDze1ovIL3lXGZf",
    sourceType: "spotify",
    attribution: "Spotify — PH87 official artist photo",
    spotifyArtistId: "6w8j7obDDze1ovIL3lXGZf",
  },
  {
    slug: "part-time-killer",
    artistName: "Part Time Killer",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/1PDjdSn9YCXz1reA1PUcC0",
    sourceType: "spotify",
    attribution: "Spotify — Part Time Killer official artist photo",
    spotifyArtistId: "1PDjdSn9YCXz1reA1PUcC0",
  },
  {
    slug: "lucy",
    artistName: "Lucy",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/0BlPI3UKzTcN2jf0gCa0b9",
    sourceType: "spotify",
    attribution: "Spotify — Lucy (Luca Mortellaro) official artist photo",
    spotifyArtistId: "0BlPI3UKzTcN2jf0gCa0b9",
  },
  {
    slug: "victor-ruiz",
    artistName: "Victor Ruiz",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/0xgdNNa5mIbnJKp8AG8S4z",
    sourceType: "spotify",
    attribution: "Spotify — Victor Ruiz official artist photo",
    spotifyArtistId: "0xgdNNa5mIbnJKp8AG8S4z",
  },
  {
    slug: "josh-wink",
    artistName: "Josh Wink",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/6DQLkRykAsF6paJnlIMX4H",
    sourceType: "spotify",
    attribution: "Spotify — Josh Wink official artist photo",
    spotifyArtistId: "6DQLkRykAsF6paJnlIMX4H",
  },
  {
    slug: "dave-the-drummer",
    artistName: "D.A.V.E. The Drummer",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/4ulxN8QnUlk3bX6IopQO7C",
    sourceType: "spotify",
    attribution: "Spotify — D.A.V.E. The Drummer official artist photo",
    spotifyArtistId: "4ulxN8QnUlk3bX6IopQO7C",
  },
  {
    slug: "paranoid-london",
    artistName: "Paranoid London",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/0KyUH5WmspOhuIQAnw42Fb",
    sourceType: "spotify",
    attribution: "Spotify — Paranoid London official artist photo",
    spotifyArtistId: "0KyUH5WmspOhuIQAnw42Fb",
  },
  {
    slug: "randomer",
    artistName: "Randomer",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/7K0WJzyqUNRhraNcsvJp1h",
    sourceType: "spotify",
    attribution: "Spotify — Randomer official artist photo",
    spotifyArtistId: "7K0WJzyqUNRhraNcsvJp1h",
  },
  {
    slug: "front-242",
    artistName: "Front 242",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/2tyMOS8xKREgpEwHnLc6EX",
    sourceType: "spotify",
    attribution: "Spotify — Front 242 official artist photo",
    spotifyArtistId: "2tyMOS8xKREgpEwHnLc6EX",
  },
  {
    slug: "norbak",
    artistName: "Nørbak",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/0TwXWZcwzGVVOa1Vdu3UEj",
    sourceType: "spotify",
    attribution: "Spotify — Nørbak official artist photo",
    spotifyArtistId: "0TwXWZcwzGVVOa1Vdu3UEj",
  },
  {
    slug: "mcr-t",
    artistName: "MCR-T",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/4m7q9onIm2bqhwHy9utqmw",
    sourceType: "spotify",
    attribution: "Spotify — MCR-T official artist photo",
    spotifyArtistId: "4m7q9onIm2bqhwHy9utqmw",
  },
  {
    slug: "hector-oaks",
    artistName: "Héctor Oaks",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/2FZAQdFEANNv5Gi29PI10x",
    sourceType: "spotify",
    attribution: "Spotify — Héctor Oaks official artist photo",
    spotifyArtistId: "2FZAQdFEANNv5Gi29PI10x",
  },
  {
    slug: "ansome",
    artistName: "Ansome",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/14gRo11WOeTXBDcgFr8Ejb",
    sourceType: "spotify",
    attribution: "Spotify — Ansome (Kieran Whitefield) official artist photo",
    spotifyArtistId: "14gRo11WOeTXBDcgFr8Ejb",
  },
  {
    slug: "alex-bau",
    artistName: "Alex Bau",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/0NepOrVsrboBKYECeSmwak",
    sourceType: "spotify",
    attribution: "Spotify — Alex Bau official artist photo",
    spotifyArtistId: "0NepOrVsrboBKYECeSmwak",
  },
  {
    slug: "deepbass",
    artistName: "Deepbass",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/4JBXPj21sTqOZvgQurUJoP",
    sourceType: "spotify",
    attribution: "Spotify — Deepbass (Darren Roberts) official artist photo",
    spotifyArtistId: "4JBXPj21sTqOZvgQurUJoP",
  },
  {
    slug: "petduo",
    artistName: "Petduo",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/5SEUYqumyvmrkgWpOco1lo",
    sourceType: "spotify",
    attribution: "Spotify — PETDuo official artist photo",
    spotifyArtistId: "5SEUYqumyvmrkgWpOco1lo",
  },
  {
    slug: "lft",
    artistName: "L.F.T.",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/0CxkG7EdCzA4QJoDeiODFP",
    sourceType: "spotify",
    attribution: "Spotify — L.F.T. official artist photo",
    spotifyArtistId: "0CxkG7EdCzA4QJoDeiODFP",
  },
  {
    slug: "hante",
    artistName: "Hante",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/5PhSiNjHZevtfAj9zmvVkU",
    sourceType: "spotify",
    attribution: "Spotify — Hante. (Hélène de Thoury) official artist photo",
    spotifyArtistId: "5PhSiNjHZevtfAj9zmvVkU",
  },
  {
    slug: "weichentechnikk",
    artistName: "Weichentechnikk",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/3sIkF6FOnvaaA9nLCnITrh",
    sourceType: "spotify",
    attribution: "Spotify — Weichentechnikk (Stefan Wietek) official artist photo",
    spotifyArtistId: "3sIkF6FOnvaaA9nLCnITrh",
  },
  {
    slug: "petra-flurr",
    artistName: "Petra Flurr",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/51exL0KZS30QQSJd9osmig",
    sourceType: "spotify",
    attribution: "Spotify — Petra Flurr official artist photo",
    spotifyArtistId: "51exL0KZS30QQSJd9osmig",
  },
  {
    slug: "rumina",
    artistName: "Rumina",
    source: "spotify-official",
    sourceUrl: "https://open.spotify.com/artist/7IDiYtKojSbRAaf2b2Mpew",
    sourceType: "spotify",
    attribution: "Spotify — Rumina official artist photo",
    spotifyArtistId: "7IDiYtKojSbRAaf2b2Mpew",
  },
  {
    slug: "per-sona",
    artistName: "Per-sona",
    source: "spotify-official",
    sourceUrl: "https://persona0101.bandcamp.com",
    sourceType: "official-website",
    attribution: "Bandcamp — PERSONA (Rome) official artist photo; stylized slug per-sona",
  },
];

const VERIFIED_AT = "2026-06-29";

export function researchedPortraitPath(slug: string): string {
  return `/images/portraits/researched/${slug}.jpg`;
}

export const RESEARCHED_VERIFIED_PORTRAITS: VerifiedImageRecord[] =
  RESEARCHED_PORTRAIT_SEEDS.map((seed) => ({
    slug: seed.slug,
    artistName: seed.artistName,
    imageUrl: researchedPortraitPath(seed.slug),
    imageSource: seed.sourceUrl,
    sourceType: seed.sourceType,
    attribution: seed.attribution,
    lastVerifiedAt: VERIFIED_AT,
    imageVerified: true as const,
    crossChecks: {
      nameMatch: true,
      spotifyArtistIdMatch: seed.sourceType === "spotify" ? true : undefined,
      handleMatch: seed.sourceType === "resident-advisor" ? true : undefined,
      identityConfirmed: true,
    },
    verificationNotes: `Deep portrait research (${seed.source}) — local asset in public/images/portraits/researched/`,
  }));

export function getResearchedPortraitSlugs(): string[] {
  return RESEARCHED_PORTRAIT_SEEDS.map((s) => s.slug);
}
